//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appharbor_SQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hocsinh
    {
        public string IDSinhVien { get; set; }
        public string Ten { get; set; }
        public string Email { get; set; }
    }
}
